
=== Course Policies

The purpose of our course work is to give you hands on experience with the topics
from class. Most of this work will be due in lecture or labs. The  
weekly time commitment for this course is aimed to be 10 hours per week.

*Late Policy*

You may request up to 2 late days on an assignment, provided you give advance 
notice ahead of time (e.g. plan ahead to see if/when you need more time for an assignment).  Your lowest assignment grade will be dropped.  

*Resubmission Policy*

In some cases, it is possible to re-submit course work to recover lost points due to errors. However, you may not re-submit work for which you have no initial submission. Nor will we accept re-submissions that are incomplete or show little improvement from the original. If you resubmit work, you must strive for full marks. You will need permission from the instructor to re-submit work.

*Missed Quiz Policy*

If you need to miss a quiz, you must make arrangements ahead of time to take it
later. If you cannot give notice ahead of time because of a medical emergency,
you will need to provide a doctor's note to schedule a make-up quiz.
