include::header.adoc[]

:title: Understanding splines
:Author Initials: ASN
:Date:    2020-02-07
:Revision: 0.1
:stem: latexmath

[discrete]
= {title}

[discrete]
= Name: 

*Due September 30th, in class*

This worksheet is intended as a short 30 min exercise to be done in groups of 2-3 people.

[discrete]
= Catmull-ROM splines

Consider a cubic Catmull-ROM spline with data points at 

* stem:[p_0 = (0, 0)^T] 
* stem:[p_1 = (1, 1)^T] 
* stem:[p_2 = (2, 0)^T] 

1) Draw the data points

{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +

2) How many segments does the spline have?

{nbsp} +
{nbsp} +

3) To ensure C1 continuity, what equations should we use to compute four control
points for each interior segment of the spline? What about the endpoints?

{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +

4) Compute the control points for segment 0 (the first segment). Draw the control points above.


{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +

5) Compute the control points for segment 1 (the second segment). Draw the control points above.

{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +

6) Suppose each data point is uniformly spaced such that p0 is at time 0, p1 is at time 1, and p2 is at time 2. 
What is the value of the curve at p(1.5)?

[discrete]
= Hermite splines

Recall that for Hermite splines, each segment is interpolated using the 
two endpoints stem:[p_1] and stem:[p_2] along with the slopes at each 
point.

We will derive the process for computing 
slopes which give us C2 continuity at each input key. 

Our goal is to have 

[stem]
++++
f_i^{''}(1) = f_{i+1}^{''}(0) 
++++

>Our approach is to derive expressions for stem:[f^{''}(0)]
and stem:[f^{''}(1)] then use these expressions to setup a system of 
linear equations to solve for stem:[p_i^{'}]  

Recall that the equation for interpolating with a Hermite spline is 

[stem]
++++
f(t) = p_i H_0^3(t) + p_i^{'} H_1^3(t) + p_{i+1}^{'} H_2^3(t) + p_{i+1} H_3^3(t)
++++

where

[stem]
++++
\begin{align*}
H_0^3(t) &= 1 - 3 t^2 + 2 t^3 \\
H_1^3(t) &= t - 2 t^2 + t^3  \\
H_2^3(t) &= -t^2 + t^3  \\
H_3^3(t) &= 3 t^2 - 2 t^3
\end{align*}
++++


* What is stem:[f^{''}(t)]?

{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +

* What is stem:[f_{i+1}^{''}(0)]?

{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +

* What is stem:[f_i^{''}(1)] ?

{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +

* We want stem:[f_i^{''}(1) = f_{i+1}^{''}(0)]. Substitute the expressions from the previous two questions into this equation.

{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +

* In the previous question, which variables are unknowns and which are known?

{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +

* Rearrange the terms from question 4 so that the unknown variables are on the right hand side and the known variables are on the left hand side. This equation tells us the relationship between the input keys and the slopes at each key.

{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +


* Suppose we have a Hermite spline with 5 points

				p0 = (0,0,0)
				p1 = (1,2,0)
				p2 = (3,3,0)
				p3 = (6,3,0)
				p4 = (8,0,0)

Plug in these points into your equation for question 6. You can define three 
equations that we can use to solve for the slopes. 


* Put the equations from the previous question in matrix form P = A P'. 

[stem]
++++
P = 
\left[
\begin{array}{c}
f_{key}(p_0,p_2)\\
f_{key}(p_1,p_3)\\
f_{key}(p_2,p_4)
\end{array}
\right]

A = 
\left[
\begin{array}{ccccc}
a_{11} & a_{12} & a_{13} & 0 & 0\\
0 & a_{22} & a_{23} & a_{24} & 0\\
0 & 0 & a_{33} & a_{34} & a_{35} 
\end{array}
\right]

P' = 
\left[
\begin{array}{c}
p^{'}_0\\
p^{'}_1\\
p^{'}_2\\
p^{'}_3\\
p^{'}_4
\end{array}
\right]
++++

A is a 3x5 matrix, P' is a 5x3 matrix of the slopes and P is a 3x3 matrix of vectors. What are the 
values for each row of P?  What are the values of each stem:[a_{ij}]?

{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +

How can we augment the above matrix to support clamped endpoint conditions?

{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +

How can we augment the above matrix to support natural endpoint conditions?

{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +